name: tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.8"
            matplotlib: "matplotlib==3.7.5"
          - python-version: "3.9"
            matplotlib: "matplotlib"
          - python-version: "3.12"
            matplotlib: "matplotlib"
          - python-version: "3.12"
            matplotlib: "matplotlib"
            plotly: "git+https://github.com/plotly/plotly.py"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: pip install -e ".[dev]" "${{ matrix.matplotlib }}" ${{ matrix.plotly }}
      - name: Test
        run: python -m pytest -q
